### ISSUE TITLE
Some tests are reliant on jaraco's local dev environment or test ordering

### ISSUE THREAD

**Issue by jaraco** [jaraco/jaraco.develop#14]
> Because `git.resolve()` is called regardless of the `git_url_substitutions` fixture, tests are failing. Maybe delaying the execution of `github.Repo.detect()` by making it run lazily under functions' parameters and marking the fixture with `autouse=True` is a way to go?

I don't yet understand why this issue emerges with this change. Oh, maybe it's because of non-isolated tests (some test currently invokes git_url_substitutions, whose effect persists beyond the test scope, then the tests for `resolve` are run).

Except, no, that doesn't seem to be the case:

<details>

```
 jaraco.develop main @ tox -q -- -p no:cov -k resolve
============================================================== test session starts ===============================================================
platform darwin -- Python 3.12.2, pytest-8.0.2, pluggy-1.4.0
cachedir: .tox/py/.pytest_cache
rootdir: /Users/jaraco/code/jaraco/jaraco.develop
configfile: pytest.ini
plugins: enabler-3.0.0, checkdocs-2.10.1, mypy-0.10.3, subprocess-1.5.0, ruff-0.2.1
collected 88 items / 87 deselected / 1 selected                                                                                                  

jaraco/develop/git.py .                                                                                                                    [100%]

================================================================ warnings summary ================================================================
jaraco/develop/git.py::develop.git.resolve
  /Users/jaraco/code/jaraco/jaraco.develop/jaraco/develop/git.py:67: EncodingWarning: 'encoding' argument not specified.
    lines = subprocess.check_output(cmd, text=True)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================================================== 1 passed, 87 deselected, 1 warning in 8.49s ===================================================
.pkg: _exit> python '/Users/jaraco/Library/Application Support/pipx/venvs/tox/lib/python3.12/site-packages/pyproject_api/_backend.py' True setuptools.build_meta
  py: OK (9.08=setup[0.44]+cmd[8.64] seconds)
  congratulations :) (9.12 seconds)
```

</details>

Oh. Maybe that's because my dev environment is configured with those substitutions and the issue is that the tests aren't running in isolation of my local dev environment. I recently ran into this [issue in another project](https://gerrit.googlesource.com/git-repo/+/024df06ec15d7304fbb5f9a2b1aa44f2af9daf4c). Let me see if I can't apply something like that here and then see if the tests fail (in isolation or not).

Edit: Interesting! The warning emitted in that output is in fact indicative of the subprocess call being made without being patched, _confirming_ that the fixture isn't intercepting those calls and the test suite is in fact dependent on my local dev environment.

**Comment by jaraco** [comment]
After applying 9394417, I can confirm that the tests fail if run in isolation:

<details>

```
 jaraco.develop tests/isolated-home @ tox -q -- -p no:cov -k resolve
============================================================== test session starts ===============================================================
platform darwin -- Python 3.12.2, pytest-8.0.2, pluggy-1.4.0
cachedir: .tox/py/.pytest_cache
rootdir: /Users/jaraco/code/jaraco/jaraco.develop
configfile: pytest.ini
plugins: enabler-3.0.0, checkdocs-2.10.1, mypy-0.10.3, subprocess-1.5.0, home-0.5.1, ruff-0.2.1
collected 88 items / 87 deselected / 1 selected                                                                                                  

jaraco/develop/git.py F                                                                                                                    [100%]

==================================================================== FAILURES ====================================================================
_________________________________________________________ [doctest] develop.git.resolve __________________________________________________________
133 
134     >>> projects = list(map(resolve, projects()))
UNEXPECTED EXCEPTION: CalledProcessError(1, ['git', 'config', '--get-regexp', 'url\\..*\\.insteadof'])
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/doctest.py", line 1361, in __run
    exec(compile(example.source, filename, "single",
  File "<doctest develop.git.resolve[0]>", line 1, in <module>
  File "/Users/jaraco/code/jaraco/jaraco.develop/jaraco/develop/git.py", line 141, in resolve
    return default.join(name)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/jaraco/code/jaraco/jaraco.develop/jaraco/develop/git.py", line 101, in join
    return URL(urllib.parse.urljoin(self.resolved, path)).applied
                                    ^^^^^^^^^^^^^
  File "/Users/jaraco/code/jaraco/jaraco.develop/jaraco/develop/git.py", line 94, in resolved
    return URL(self.scheme.resolve(self))
               ^^^^^^^^^^^
  File "/Users/jaraco/code/jaraco/jaraco.develop/jaraco/develop/git.py", line 90, in scheme
    return URLScheme.lookup(self)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jaraco/code/jaraco/jaraco.develop/jaraco/develop/git.py", line 72, in lookup
    checks = (scheme for scheme in cls.load() if scheme.matches(url))
                                   ^^^^^^^^^^
  File "/Users/jaraco/code/jaraco/jaraco.develop/jaraco/develop/git.py", line 67, in load
    lines = subprocess.check_output(cmd, text=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'config', '--get-regexp', 'url\\..*\\.insteadof']' returned non-zero exit status 1.
/Users/jaraco/code/jaraco/jaraco.develop/jaraco/develop/git.py:134: UnexpectedException
================================================================ warnings summary ================================================================
jaraco/develop/git.py::develop.git.resolve
  /Users/jaraco/code/jaraco/jaraco.develop/jaraco/develop/git.py:67: EncodingWarning: 'encoding' argument not specified.
    lines = subprocess.check_output(cmd, text=True)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================================================ short test summary info =============================================================
FAILED jaraco/develop/git.py::develop.git.resolve
================================================== 1 failed, 87 deselected, 1 warning in 8.38s ===================================================
py: exit 1 (8.56 seconds) /Users/jaraco/code/jaraco/jaraco.develop> pytest -p no:cov -k resolve pid=50108
  py: FAIL code 1 (9.20 seconds)
  evaluation failed :( (9.26 seconds)
```

</details>
